### ISSUE TITLE
SSR fails to get first page of infinite hits after filter change

### ISSUE THREAD

**Issue by ayuhito** [algolia/instantsearch#5628] opened 2023-05-14 19:17 UTC
### 🐛 Current behavior

Using Remix SSR, `useInfiniteHits` and `useConfigure` loses the first page of results after setting a filter. This includes the filtered result which is missing the first page of results, as well as after removing the filter changing the original results.

Things get a little more broken if you load more hits and then use the filter. You end up losing more pages of hits as you start from the last loaded page.

To workaround, removing the `InstantSearchSSRProvider` and `getServerState` does work, but removes SSR capabilities which isn't ideal.

### 🔍 Steps to reproduce

1. Go to reproduction.
2. Click Set Filter (note that there should be 10 results on the first page)
3. Click Set Filter again to revert to the original unfiltered results. You can now see the first result starts off with `_position: 11`.

If you scroll down to trigger showing more results and repeat the set filter process, the starting position numbers get increasingly larger.

You can also check out https://fontsource.org/ which is an ongoing project I'm working on for a more visual representation. Toggling `show only variable fonts` shows the same behaviour. (Edit: have disabled SSR for the time being)

### Live reproduction

https://codesandbox.io/p/sandbox/adoring-bohr-8lhjnx

### 💭 Expected behavior

The first page of hits should be visible.

### Package version

"algoliasearch": "^4.17.0",  "instantsearch.js": "^4.55.0",  "react": "^18.2.0",  "react-dom": "^18.2.0",  "react-instantsearch-hooks-server": "^6.43.0",  "react-instantsearch-hooks-web": "^6.43.0"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SLMNBJ** [comment] 2023-07-25 05:54
Having a similar issue with Next.js. Using a custom routing, the refinement list get ignored with getServerState

**Comment by ayuhito** [comment] 2023-10-03 12:11
I'm still able to reproduce this with the latest stack with react-instantsearch@7.

**Comment by Haroenv** [comment] 2023-12-07 11:02
All other widgets set the page to 0, only configure doesn't as many parameters you could change don't need to reset the page. I recommend you also have a look at useMenu, useRefinementList instead of useConfigure, as it will play nice with eg. routing too.

As you've found the solution and this is by design I'll close the issue now.

**Closed by Haroenv** 2023-12-07 11:02 UTC
Labels: triage
