### ISSUE TITLE
Pagination link hrefs not consistent server and client side

### ISSUE THREAD

**Issue by richardweaver** [algolia/instantsearch#5597] opened 2023-04-14 14:07 UTC
### 🐛 Current behavior

When rendering the <Pagination /> component server-side the URLs in the href attribute do not include the relevant query parameters for pagination. When hydrated client-side they do.

I am using the `react-instantsearch-hooks-router-nextjs` library with a custom route state object and `createURL` function. 

Server rendered code:
```html
      <div class="pagination">
            <div class="ais-Pagination">
              <ul class="ais-Pagination-list">
                <li
                  class="ais-Pagination-item ais-Pagination-item--disabled ais-Pagination-item--firstPage">
                  <span class="ais-Pagination-link" aria-label="First">‹‹</span>
                </li>
                <li
                  class="ais-Pagination-item ais-Pagination-item--disabled ais-Pagination-item--previousPage">
                  <span class="ais-Pagination-link" aria-label="Previous">‹</span>
                </li>
                <li
                  class="ais-Pagination-item ais-Pagination-item--page ais-Pagination-item--selected">
                  <a class="ais-Pagination-link" href="/" aria-label="Page 1">1</a>
                </li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/" aria-label="Page 2">2</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/" aria-label="Page 3">3</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/" aria-label="Page 4">4</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/" aria-label="Page 5">5</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/" aria-label="Page 6">6</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/" aria-label="Page 7">7</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--nextPage"><a
                    class="ais-Pagination-link" href="/" aria-label="Next">›</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--lastPage"><a
                    class="ais-Pagination-link" href="/" aria-label="Last">››</a></li>
              </ul>
            </div>
          </div>
        </div>
```

Client-rendered:
```html
          <div class="pagination">
            <div class="ais-Pagination">
              <ul class="ais-Pagination-list">
                <li
                  class="ais-Pagination-item ais-Pagination-item--disabled ais-Pagination-item--firstPage">
                  <span class="ais-Pagination-link" aria-label="First">‹‹</span>
                </li>
                <li
                  class="ais-Pagination-item ais-Pagination-item--disabled ais-Pagination-item--previousPage">
                  <span class="ais-Pagination-link" aria-label="Previous">‹</span>
                </li>
                <li
                  class="ais-Pagination-item ais-Pagination-item--page ais-Pagination-item--selected">
                  <a class="ais-Pagination-link" href="/" aria-label="Page 1">1</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/?p_page=2" aria-label="Page 2">2</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/?p_page=3" aria-label="Page 3">3</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/?p_page=4" aria-label="Page 4">4</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/?p_page=5" aria-label="Page 5">5</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/?p_page=6" aria-label="Page 6">6</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--page"><a
                    class="ais-Pagination-link" href="/?p_page=7" aria-label="Page 7">7</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--nextPage"><a
                    class="ais-Pagination-link" href="/?p_page=2" aria-label="Next">›</a></li>
                <li class="ais-Pagination-item ais-Pagination-item--lastPage"><a
                    class="ais-Pagination-link" href="/?p_page=125" aria-label="Last">››</a></li>
              </ul>
            </div>
          </div>
```

### 🔍 Steps to reproduce

1. Implement Next.js SSR with `react-instantsearch-hooks-router-nextjs`
2. Deploy <Pagination />
3. Use a custom createURL function

### Live reproduction

https://github.com/richardweaver/algolia-pagination-ssr-issue

### 💭 Expected behavior

<Pagination /> should render identically on server- and client-side.

### Package version

react-instantsearch-hooks-server / react-instantsearch-hooks-web / react-instantsearch-hooks-router-nextjs 6.42.2

### Operating system

macOS 13.3.1

### Browser

Chrome 112.0.5615.49

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by avremel** [comment] 2023-05-29 02:59
Duplicate of https://github.com/algolia/instantsearch/issues/5236

**Comment by aymeric-giraudet** [comment] 2023-06-30 07:52
Hi !

This is indeed a duplicate of #5236, so I'm closing this one.
A fix is coming soon and you'll be informed there.

**Closed by aymeric-giraudet** 2023-06-30 07:52 UTC
Labels: triage
