### ISSUE TITLE
NextJS - `createURL` should run server side

### ISSUE THREAD

**Issue by avremel** [algolia/instantsearch#5656] opened 2023-05-31 16:11 UTC
### 🐛 Current behavior

`createURL` returns an empty URL on the server and only populates on the client.

### 🔍 Steps to reproduce

1. Go the sandbox
2. Disable Javascript
3. Observe that the links are empty
<img width="376" alt="Screen Shot 2023-05-31 at 12 09 06 PM" src="https://github.com/algolia/instantsearch/assets/10588097/3bcd0dbd-9231-4874-8cfa-7fcc66c52b61">

### Live reproduction

https://codesandbox.io/p/sandbox/refinement-list-sort-issue-forked-i8kn3o?file=%2Fcomponents%2FRefinementList.js%3A9%2C11

### 💭 Expected behavior

Expect that the links are populated server side. Theoretically this should be possible since we are running `getServerState` on the server and know the UI state prior to SSR. (See https://github.com/algolia/instantsearch/issues/5236#issuecomment-1566414241).

### Package version

algoliasearch 4.17.1, react-instantsearch-hooks-web 6.44.0

### Operating system

Mac 11.6.5

### Browser

Chrome 113.0.5672.126

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by avremel** [comment] 2023-06-20 17:48
A side effect of this issue: When you click on a link before the JS is fully loaded, you are taken to the broken link.

**Comment by aymeric-giraudet** [comment] 2023-06-30 07:46
Hi @avremel,

Closing this as it's a duplicate of #5236. The fix is coming soon and we'll communicate about it there !

**Closed by aymeric-giraudet** 2023-06-30 07:46 UTC
Labels: triage
