### ISSUE TITLE
<Configure /> types wrong or conflict with documentation 

### ISSUE THREAD

**Issue by stwilz** [algolia/instantsearch#5989] opened 2024-01-06 00:58 UTC
### 🐛 Current behavior

In the documentation here,
https://www.algolia.com/doc/api-reference/widgets/configure/react/#widget-param-searchparameters

it outlines that you should be able to define a filter on the Configure component like so,
```
<Configure
  analytics={false}
  filters="free_shipping:true"
  hitsPerPage={40}
/>
```

Which does work as expected but when implemented in Typescript the following type error appears,
`'filters' does not exist in type 'PlainSearchParameters'`.

Are we potentially not implementing this correctly, could it be and issue with using `react-instantsearch-nextjs` or is there a problem with the libraries types? 

Thanks!

### 🔍 Steps to reproduce

1. Create Next 14 boilerplate with typescript
2. Install react-instantsearch & react-instantsearch-nextjs
3. Implement Intant Search and Configure

### Live reproduction

...

### 💭 Expected behavior

This is a development issue. No live preview required.

### Package version

7.5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Haroenv** [comment] 2024-01-07 18:29
I believe you haven't installed `algoliasearch`, can you check that? There should be a warning in the install message too

**Comment by stwilz** [comment] 2024-01-07 21:19
Can confirm we have been using `algoliasearch` `4.22.0`

```
'use client';

import { Configure, ConfigureProps, Hits } from 'react-instantsearch';

import algoliasearch from 'algoliasearch';
import { InstantSearchNext } from 'react-instantsearch-nextjs';

const searchIndex = new String(
  process.env.NEXT_PUBLIC_ALGOLIA_INDEX_NAME
).toString();

export const client = algoliasearch(
  process.env.NEXT_PUBLIC_ALGOLIA_APP_ID!,
  process.env.NEXT_PUBLIC_ALGOLIA_API_KEY!
);

export function AlgoliaFacetSearch({
  primaryFacet = '',
  query = '',
  tags = [],
}) {
  const configureProps = {
    filters: `type:"${primaryFacet}"`,
    facets: ['*'],
    query: query,
    tagRefinements: tags,
    facetingAfterDistinct: true,
    hitsPerPage: 40,
  } as ConfigureProps;

  return (
    <InstantSearchNext
      indexName={searchIndex}
      searchClient={client}
      future={{
        preserveSharedStateOnUnmount: true,
      }}
    >
      <Hits />
      <Configure {...configureProps} />
    </InstantSearchNext>
  );
}

```

**Comment by Haroenv** [comment] 2024-01-08 09:14
Hey, I copied your code standalone, and everything seems to be working? Is there any package that could be stuck at an older version? Even transitive ones like `algoliasearch-helper` for example.

Here's my reproduction that has no typescript error: https://codesandbox.io/p/devbox/configure-works-nrlt73

**Comment by stwilz** [comment] 2024-01-10 07:09
Our code works because we cast `configureProps as ConfigureProps`. codesandbox doesn't seem to be displaying type errors. I'll create a local copy, run in VSCode and get back to you.

**Comment by flevi29** [comment] 2024-02-13 10:16
All I know is that I reverted my update only on `instantsearch.js` from .3 to .1 and then it worked. But now that I'm trying to reproduce it, it no longer happens, for whatever reason.

I know that it was printing something like `hitsPerPage doesn't exist on PlainSearchParameters & object`, where `PlainSearchParameters extends SearchOptions` and `SearchOptions` might come from something weird and hacky that I don't know what to think about `PickForClient` with tons of `@ts-ignore`s. Doing stuff like this might very well cause unexpected and erratic behavior.

**Comment by Haroenv** [comment] 2024-02-13 10:45
Sure, PickForClient is there to support many use cases for different versions of `algoliasearch` and ensuring that the parameters are maintained in a single place only. There however haven't been any changes to this code in a long time (definitely not between the last three patches of InstantSearch.js), so maybe it's a typescript compiler cache thing where it was evaluating just when you were reinstalling and thus there was no `algoliasearch`? If you can reproduce consistently we'll fix it of course

**Comment by Ra0R** [comment] 2024-05-10 10:07
I was having the same issue. I think it might not be related to any changes within the library.
Initially I was not having the issue locally, but when building on the build server the error would arise. 

Differences could potentially be, node version, yarn version or typescript version? (I was using an older version of node locally and the error was not arising).

**Comment by Ra0R** [comment] 2024-05-15 10:26
@Haroenv I did not, I used the workaround by casting it to the correct type.

I am not sure what causes the issue.

**Comment by S-Blank** [comment] 2024-06-20 08:26
I've encountered an issue with `hitsPerPage`.

Here's my code:
```jsx
<Configure hitsPerPage={5} />
```

TypeScript gives me the following error:
```
Type '{ hitsPerPage: number; }' is not assignable to type 'IntrinsicAttributes & PlainSearchParameters'.
Property 'hitsPerPage' does not exist on type 'IntrinsicAttributes & PlainSearchParameters'.ts(2322)
```

Installed packages:
- `"react-instantsearch": "^7.11.3"`
- `"algoliasearch": "^4.23.1"`

Any help on resolving this issue would be greatly appreciated!

**Comment by S-Blank** [comment] 2024-06-20 08:34
@Haroenv Here is my code:

```tsx
"use client";

import algoliasearch from "algoliasearch/lite";
import { InstantSearch, SearchBox, Hits, Configure } from "react-instantsearch";
import Image from "next/image";

const searchClient = algoliasearch("###", "###");

const Hit = ({
  hit,
}: {
  hit: { id: string; name: string; imageSrc: string; shopId: string };
}) => {
  return (
    <article>
      <Image
        src={hit.imageSrc}
        alt={hit.name}
        width={100}
        height={100}
        className="h-10"
      />
      <p>{hit.name}</p>
    </article>
  );
};

const Search = () => {
  return (
    <InstantSearch searchClient={searchClient} indexName="indexName" insights>
      <SearchBox />
      <Configure hitsPerPage={5} />
      <Hits hitComponent={Hit} />
    </InstantSearch>
  );
};

export default Search;
```

**Comment by Ra0R** [comment] 2024-06-20 08:40
> @Haroenv Here is my code:
> 
> ```tsx
> "use client";
> 
> import algoliasearch from "algoliasearch/lite";
> import { InstantSearch, SearchBox, Hits, Configure } from "react-instantsearch";
> import Image from "next/image";
> 
> const searchClient = algoliasearch("###", "###");
> 
> const Hit = ({
>   hit,
> }: {
>   hit: { id: string; name: string; imageSrc: string; shopId: string };
> }) => {
>   return (
>     <article>
>       <Image
>         src={hit.imageSrc}
>         alt={hit.name}
>         width={100}
>         height={100}
>         className="h-10"
>       />
>       <p>{hit.name}</p>
>     </article>
>   );
> };
> 
> const Search = () => {
>   return (
>     <InstantSearch searchClient={searchClient} indexName="indexName" insights>
>       <SearchBox />
>       <Configure hitsPerPage={5} />
>       <Hits hitComponent={Hit} />
>     </InstantSearch>
>   );
> };
> 
> export default Search;
> ```



> I've encountered an issue with `hitsPerPage`.
> 
> Here's my code:
> 
> ```js
> <Configure hitsPerPage={5} />
> ```
> 
> TypeScript gives me the following error:
> 
> ```
> Type '{ hitsPerPage: number; }' is not assignable to type 'IntrinsicAttributes & PlainSearchParameters'.
> Property 'hitsPerPage' does not exist on type 'IntrinsicAttributes & PlainSearchParameters'.ts(2322)
> ```
> 
> Installed packages:
> 
>     * `"react-instantsearch": "^7.11.2"`
> 
>     * `"algoliasearch": "^4.23.3"`
> 
> 
> Any help on resolving this issue would be greatly appreciated!

You can define the following
```
	const configureProps = {
		hitsPerPage: 12,
		// filters: 'price>0',
		// query: initialQuery
	} as ConfigureProps;
...
<Configure {...configureProps} />
```

**Comment by S-Blank** [comment] 2024-06-20 08:42
@Ra0R Yes, this actually works without errors. Thank you.

**Comment by Haroenv** [comment] 2024-06-20 10:00
I've found what is going on, but oddly this never happened inside the repo, even after updating the typescript version (in future reference, please create a reproducible example, at least a sandbox or a GitHub repo).

You can follow the fix in #6244

**Closed** 2024-06-20 10:56 UTC
Labels: triage

**Comment by JannikZed** [comment] 2024-07-02 14:24
We are using typescript 5.4.5 and react-instantsearch 7.11.3 and get exactly this error: 
```
<Configure hitsPerPage={5} />
```
```
Type '{ hitsPerPage: number; }' is not assignable to type 'IntrinsicAttributes & PlainSearchParameters'.
  Property 'hitsPerPage' does not exist on type 'IntrinsicAttributes & PlainSearchParameters'.
  ``` 
doesn't seem to be fixed?

**Comment by Haroenv** [comment] 2024-07-02 15:11
Can you give a reproduction then @JannikZed?

**Comment by kart-c** [comment] 2024-09-18 18:29
Hey @Haroenv I am facing this issue where the `<Configure />` is giving type errors. Attaching a small video of the same.

https://github.com/user-attachments/assets/e5287761-9b19-4aac-9a92-24cc1d90268f

For reference, here is the dependency versions

```json
  "dependencies": {
    "typesense-instantsearch-adapter": "^2.8.0"
  },
  "devDependencies": {
    "typescript": "^5"
  }
```

Let me know if I am missing something here.

**Comment by Haroenv** [comment] 2024-09-19 06:50
Clearly a bug in the typesense adapter and thus should be opened there.

**Comment by kart-c** [comment] 2024-09-19 07:53
Sorry I missed adding the `react-instantsearch` package version in the above comment
```json
"react-instantsearch": "^7.13.1"
```

Since the `<Configure />` is being imported from `react-instantsearch` I thought it might be an issue with the `instantsearch` library.

**Comment by Haroenv** [comment] 2024-09-19 08:39
No it's not as typesense is likely messing up the types. Open issue there, this is the repository for Algolia

**Comment by czmarcos** [comment] 2024-10-30 22:27
@Haroenv any fix on this?
I am getting similar error with distinct attribute
